### PR TITLE
Updated logo, added Richard, updated contact, created submissions page

### PR DESCRIPTION
**Pull request by novoio**
- Updated website logo - logo.svg
- Added Richard to the Team section
- Added Richard's bio: people/richard.html
- Removed facebook: contact.html
- Updated date to 2020 at bottom of page
- Updated bottom contact to info@cppalliance.org
- Added proposal page - proposals.html
- Replaced images/cpp.jpg with cpp.png

### CODE REVIEW

**Comment by vinniefalco** [comment]
`cpp.png` uses an image copyright by Getty Images, which we don't have permission to, and the watermark is even present in the file...

**Comment by novoio** [comment]
`cpp.png` was given by @louistatta

**Comment by vinniefalco** [comment]
Sorry, just remove the image please. This was my fault, a miscommunication.

**Comment by novoio** [comment]
Do we need to put it back to the previous `cpp.jpg`?

**Comment by vinniefalco** [comment]
No you can just delete both files, since they arent used.

**Comment by novoio** [comment]
Got it

**Comment by novoio** [comment]
The next commit should also be rebased ?

**Comment by vinniefalco** [comment]
> The next commit should also be rebased ?

Squash it all down

**Comment by novoio** [comment]
Ok

**Comment by vinniefalco** [comment]
Please change the first line of the commit message to `Various site updates:` including the trailing colon

**Comment by novoio** [comment]
Got it.

**Comment by novoio** [comment]
Just updated the commit message.

**Pull request merged**
