### PR TITLE
update HTML

### PR DESCRIPTION
**Pull request by AmanMishra-hub**
I have try to solve some issue I hope You Like it

### CODE REVIEW

**Comment by sdarwin** [comment]
Hi @AmanMishra-hub , was this a school assignment?

**Comment by louistatta** [comment]
The user reported for spam and blocked from repositories.

**Comment by AmanMishra-hub** [comment]
No an Compition

**Comment by AmanMishra-hub** [comment]
Pls May i give more 3 please you have to close them pls

**Comment by AmanMishra-hub** [comment]
I am requesting you pls help me once

**Pull request closed without merging**
